# Generated by Django 4.1.3 on 2022-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mri',
            name='mask',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
